/* Browser-only simulation. No backend credentials, fetches or shared database. */
(() => {
  'use strict';
  const KEY='akbars-demo-v34', ROLE='akbars-demo-role-v34';
  const roles={owner:'Главный координатор',employee:'Сотрудник СКП',coordinator:'Согласующий координатор',executive:'Наблюдатель',contractor_manager:'Менеджер подрядчика',performer:'Исполнитель'};
  const copy=x=>JSON.parse(JSON.stringify(x));
  const id=prefix=>prefix+'-'+crypto.randomUUID();
  const now=()=>new Date().toISOString();
  const date=(days)=>{const d=new Date();d.setDate(d.getDate()+days);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')+'T18:30'};
  const userFor=role=>({id:'demo-'+role,telegram_id:'demo-'+role,first_name:roles[role],last_name:'',role,organization:['contractor_manager','performer'].includes(role)?'contractor':'customer',status:'active',phone:'',notification_channels:{telegram:false,max:false},job_title:'Демонстрационный профиль'});
  function initial(){
    const services=[
      {id:'demo-host',position:'1',category:'Команда мероприятия',name:'Ведущий мероприятия',description:'Демонстрационная услуга. Работа со зрителями и проведение конкурсов.',unit:'Чел./час',price:2000,defaultQty:1,defaultPeople:1,defaultHours:3,pricing:'fixed'},
      {id:'demo-assistant',position:'2',category:'Команда мероприятия',name:'Координатор площадки',description:'Помощь участникам и контроль программы. Цена вымышленная.',unit:'Чел./час',price:1000,defaultQty:1,defaultPeople:2,defaultHours:3,pricing:'fixed'},
      {id:'demo-photo',position:'3',category:'Контент и оформление',name:'Фотосъёмка мероприятия',description:'Репортаж и обработка фотографий. Демонстрационная цена.',unit:'Усл.',price:8000,defaultQty:1,pricing:'fixed'},
      {id:'demo-zone',position:'4',category:'Контент и оформление',name:'Оформление зоны активности',description:'Подготовка и оформление игровой зоны.',unit:'компл.',price:12000,defaultQty:1,pricing:'fixed'},
      {id:'demo-artist',position:'5',category:'Шоу и выступления',name:'Выступление артиста',description:'Гонорар и организационный сбор 10%. Введите гонорар в редакторе.',unit:'Усл.',price:0,defaultQty:1,pricing:'artist_fee_plus_10'}
    ];
    const events=[['ak-bars','Ак Барс — демонстрационный матч',2],['bars','Барс — демонстрационный матч',5],['irbis','Ирбис — демонстрационный матч',8],['','Встреча болельщиков',10]].map(([team,title,day],i)=>({id:'demo-event-'+i,type:team?'match':'event',team,title,date:date(day),place:'Демонстрационная площадка',address:'',contact:'',phone:'',comment:'Вымышленное событие для тестирования',createdBy:'demo-employee',created:now()}));
    const item={id:'demo-photo',name:services[2].name,description:services[2].description,unit:'Усл.',qty:1,people:0,hours:0,unitPrice:8000,artistFee:0,note:'',lineTotal:8000};
    const calculation=(i,status)=>({id:'demo-calc-'+i,event:'draft:'+events[i].id,eventTitle:events[i].title,team:events[i].team,createdBy:'demo-employee',createdByName:'Сотрудник СКП',organization:'customer',status,total:8000,items:[copy(item)],version:1,created:now(),updated:now(),approvalRoute:'employee_vil_gleb',currentApproverRole:status==='coordinator_review'?'owner':'',routeLabel:'Главный координатор → согласующий',history:[],groupId:''});
    return {schema:1,activeSeason:{id:'demo-season',code:'26/27',createdAt:now()},events,services,calculations:[calculation(0,'coordinator_review'),calculation(3,'draft')],catalogs:[{id:'demo-catalog',name:'Демонстрационный каталог · вымышленные цены',status:'active',team:'all',count:services.length,created:now()}],standardEstimates:['ak-bars','bars','irbis'].map(team=>({id:'demo-standard-'+team,team,name:'Базовая программа · демо',seasonCode:'26/27',items:[copy(services[0]),copy(services[2])],count:2})),users:Object.keys(roles).map(userFor)};
  }
  let database;
  try{database=JSON.parse(localStorage.getItem(KEY));}catch{}
  if(!database || database.schema!==1) database=initial();
  let role=localStorage.getItem(ROLE)||'owner';if(!roles[role])role='owner';
  function save(){try{localStorage.setItem(KEY,JSON.stringify(database));}catch{throw Error('Не удалось сохранить демоданные в браузере. Проверьте доступное место.')}}
  const user=()=>database.users.find(u=>u.role===role)||userFor(role);
  const admin=()=>{if(role!=='owner')throw Error('Переключитесь на роль главного координатора в верхней панели')};
  const creator=()=>{if(!['owner','employee','coordinator'].includes(role))throw Error('Эта роль просматривает расчёты. Выберите сотрудника или координатора')};
  const workspace=()=>({ok:true,...copy(database),servicesByTeam:Object.fromEntries(['ak-bars','bars','irbis'].map(t=>[t,copy(database.services)])),calculations:copy(database.calculations.filter(c=>role==='employee'?c.createdBy===user().id:['contractor_manager','performer'].includes(role)?c.status==='approved':true))});
  function normalized(items){if(!items?.length||items.length>150)throw Error('Добавьте от 1 до 150 позиций');return items.map(item=>{const service=database.services.find(s=>s.id===item.id)||item;if(!service.name?.trim())throw Error('Укажите название позиции');const hourly=/чел/i.test(service.unit)&&/час/i.test(service.unit),artist=service.pricing==='artist_fee_plus_10';const price=Number(item.unitPrice??service.price??0),qty=Math.max(1,Number(item.qty)||1),people=Math.max(1,Number(item.people)||1),hours=Math.max(.5,Number(item.hours)||.5),fee=Number(item.artistFee)||0;if(!Number.isFinite(price)||price<0||price>100000000)throw Error('Проверьте цену');const total=artist?fee*1.1:price*(hourly?people*hours:qty);return {...copy(item),name:service.name,description:service.description||'',unit:service.unit||'Усл.',unitPrice:price,qty:artist?1:qty,people,hours,artistFee:fee,lineTotal:Math.round(total*100)/100}})}
  window.demoApi=async(path,body={})=>{
    if(path==='/api/bootstrap')return {ok:true,access:'active',user:copy(user()),isAdmin:role==='owner',isOwner:role==='owner',matches:[],...workspace()};
    if(path==='/api/workspace')return workspace();
    if(path==='/api/users'){admin();return {ok:true,users:copy(database.users)}}
    if(path==='/api/events/save'){if(user().organization!=='customer')throw Error('Создавать мероприятия могут сотрудники СКП');const incoming=body.event||{};if(!incoming.title?.trim())throw Error('Укажите название');const event={...copy(incoming),id:incoming.id||id('event'),createdBy:user().id,created:now()};const index=database.events.findIndex(e=>e.id===event.id);if(index>=0)database.events[index]=event;else database.events.push(event);save();return {ok:true,id:event.id}}
    if(path==='/api/calculations/save'){creator();const event=database.events.find(e=>'draft:'+e.id===body.eventId);if(!event)throw Error('Выберите мероприятие');const existing=database.calculations.find(c=>c.id===body.id);if(existing && !(existing.createdBy===user().id&&['draft','returned'].includes(existing.status)) && !(role==='owner'&&existing.status==='approved'))throw Error('Этот расчёт нельзя редактировать в выбранной роли');const items=normalized(body.items),total=items.reduce((sum,i)=>sum+i.lineTotal,0);const route=role==='owner'?'vil_to_gleb':role==='coordinator'?'gleb_to_vil':'employee_vil_gleb';const calculation={...(existing||{}),id:existing?.id||id('calc'),event:body.eventId,eventTitle:event.title,team:event.team||'',createdBy:existing?.createdBy||user().id,createdByName:existing?.createdByName||roles[role],organization:user().organization,status:existing?.status||'draft',items,total,version:(existing?.version||0)+1,approvalRoute:existing?.approvalRoute||route,currentApproverRole:existing?.currentApproverRole||'',routeLabel:route==='employee_vil_gleb'?'Главный координатор → согласующий':route==='vil_to_gleb'?'Согласующий координатор':'Главный координатор',groupId:body.groupId||'',created:existing?.created||now(),updated:now(),history:existing?.history||[],actualAdjusted:existing?.status==='approved'};calculation.history.push({actor_name:roles[role],action:'saved',to_status:calculation.status,comment:'Сохранено в демоверсии',created_at:now().replace('Z','')});if(existing)database.calculations.splice(database.calculations.indexOf(existing),1,calculation);else database.calculations.unshift(calculation);save();return {ok:true,id:calculation.id,total,status:calculation.status}}
    if(path==='/api/calculations/action'){const c=database.calculations.find(c=>c.id===body.id);if(!c)throw Error('Расчёт не найден');const own=c.createdBy===user().id;let next='',approver='';if(body.action==='send_approval'&&own&&['draft','returned'].includes(c.status)){creator();next=c.approvalRoute==='vil_to_gleb'?'approval':'coordinator_review';approver=c.approvalRoute==='vil_to_gleb'?'coordinator':'owner'}else if(['approve_stage','approve','return'].includes(body.action)&&c.currentApproverRole===role&&!own&&['coordinator_review','approval'].includes(c.status)){if(body.action==='return'){if(!body.comment?.trim())throw Error('Укажите причину возврата');next='returned'}else if(c.status==='coordinator_review'&&c.approvalRoute==='employee_vil_gleb'){next='approval';approver='coordinator'}else next='approved'}else if(body.action==='reopen'&&own&&['returned','cancelled'].includes(c.status))next='draft';if(!next)throw Error('Действие недоступно для текущей роли и статуса');c.history.push({actor_name:roles[role],action:body.action,from_status:c.status,to_status:next,comment:body.comment||'',created_at:now().replace('Z','')});c.status=next;c.currentApproverRole=approver;c.updated=now();c.lastComment=body.comment||'';save();return {ok:true,status:next}}
    if(path==='/api/calculations/delete'){admin();if(body.confirmation!=='УДАЛИТЬ')throw Error('Нужно подтверждение');database.calculations=database.calculations.filter(c=>c.id!==body.id);save();return {ok:true,deleted:1}}
    if(path==='/api/calculations/clear'){admin();if(body.confirmation!=='ОЧИСТИТЬ')throw Error('Нужно подтверждение');const deleted=database.calculations.length;database.calculations=[];save();return {ok:true,deleted}}
    if(path==='/api/season/create'){admin();if(body.code!==body.confirmation)throw Error('Подтвердите сезон');database.activeSeason={id:id('season'),code:body.code};database.events=[];database.calculations=[];database.services=[];database.catalogs=[];database.standardEstimates=[];save();return {ok:true,code:body.code}}
    if(path==='/api/events/import'){if(body.annualCalendar)admin();else if(user().organization!=='customer')throw Error('Недостаточно прав');let added=0;for(const incoming of body.events||[]){if(database.events.some(e=>e.title===incoming.title&&e.date===incoming.date&&e.place===incoming.place))continue;database.events.push({...copy(incoming),id:id('event'),createdBy:user().id,created:now()});added++}save();return {ok:true,added}}
    if(path==='/api/events/delete-calendar'){admin();const previous=database.events.length;database.events=database.events.filter(e=>body.importBatch?e.importBatch!==body.importBatch:!(e.type==='match'&&e.team===body.team));save();return {ok:true,deleted:previous-database.events.length}}
    if(path==='/api/catalog/import'){admin();database.catalogs.forEach(c=>c.status='archived');const catalog={id:id('catalog'),name:body.name,team:'all',status:'active',count:body.services.length,services:copy(body.services)};database.catalogs.unshift(catalog);database.services=copy(body.services);save();return {ok:true,count:body.services.length}}
    if(path==='/api/catalog/activate'){admin();const selected=database.catalogs.find(c=>c.id===body.id);if(!selected?.services)throw Error('В демо эта архивная версия недоступна');database.catalogs.forEach(c=>c.status=c.id===body.id?'active':'archived');database.services=copy(selected.services);save();return {ok:true}}
    if(path==='/api/catalog/delete'){admin();const selected=database.catalogs.find(c=>c.id===body.id);database.catalogs=database.catalogs.filter(c=>c.id!==body.id);if(selected?.status==='active')database.services=[];save();return {ok:true}}
    if(path==='/api/standard-estimates/import'){admin();database.standardEstimates=database.standardEstimates.filter(e=>e.team!==body.team);database.standardEstimates.push({...copy(body),id:id('standard'),count:body.items.length,seasonCode:database.activeSeason.code});save();return {ok:true,count:body.items.length}}
    if(path==='/api/standard-estimates/delete'){admin();database.standardEstimates=database.standardEstimates.filter(e=>e.id!==body.id);save();return {ok:true}}
    if(path==='/api/users/update'){admin();const target=database.users.find(u=>u.id===body.telegramId);if(target?.role==='owner')throw Error('Владельца нельзя изменить');if(target)Object.assign(target,{role:body.role,organization:body.organization,status:body.status||target.status});save();return {ok:true}}
    if(path.startsWith('/api/profile/')||path==='/api/users/link')throw Error('В демоверсии телефоны, привязка аккаунтов и отправка уведомлений отключены');
    throw Error('Этот сервис недоступен в локальной демоверсии');
  };
  document.addEventListener('DOMContentLoaded',()=>{
    const bar=document.createElement('aside');bar.className='demo-bar';bar.setAttribute('aria-label','Управление демоверсией');
    bar.innerHTML='<strong>ДЕМО</strong><span class="demo-note">Вымышленные данные · сохраняются только в этом браузере</span><label>Роль <select id="demoRole" aria-label="Тестовая роль"></select></label><button id="demoReset" type="button">Сбросить демо</button>';
    document.body.prepend(bar);const select=bar.querySelector('select');for(const [value,label] of Object.entries(roles)){const option=document.createElement('option');option.value=value;option.textContent=label;select.append(option)}select.value=role;
    select.addEventListener('change',()=>{localStorage.setItem(ROLE,select.value);location.reload()});bar.querySelector('button').addEventListener('click',()=>{if(confirm('Удалить только демоданные этого браузера и вернуть примеры?')){localStorage.removeItem(KEY);location.reload()}});
    const toast=document.getElementById('toast');if(toast)toast.setAttribute('aria-live','polite');
  });
})();
